ogrenciyimProje/Controllers/SorularsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using ogrenciyimProje.Data;
using ogrenciyimProje.Models;

namespace ogrenciyimProje.Controllers
{
    public class SorularsController : Controller
    {
        private readonly ApplicationDbContext _context;

        public SorularsController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: Sorulars
        [Authorize()]
        public async Task<IActionResult> Index()
        {
            return View(await _context.Sorular.ToListAsync());
        }

        // GET: Sorulars/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var sorular = await _context.Sorular
                .FirstOrDefaultAsync(m => m.ID == id);
            if (sorular == null)
            {
                return NotFound();
            }

            return View(sorular);
        }

        // GET: Sorulars/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Sorulars/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("ID,Baslik,Soru,Foto")] Sorular sorular)
        {
            if (ModelState.IsValid)
            {
                _context.Add(sorular);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(sorular);
        }

        // GET: Sorulars/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var sorular = await _context.Sorular.FindAsync(id);
            if (sorular == null)
            {
                return NotFound();
            }
            return View(sorular);
        }

        // POST: Sorulars/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("ID,Baslik,Soru,Foto")] Sorular sorular)
        {
            if (id != sorular.ID)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(sorular);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!SorularExists(sorular.ID))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(sorular);
        }

        // GET: Sorulars/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var sorular = await _context.Sorular
                .FirstOrDefaultAsync(m => m.ID == id);
            if (sorular == null)
            {
                return NotFound();
            }

            return View(sorular);
        }

        // POST: Sorulars/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var sorular = await _context.Sorular.FindAsync(id);
            _context.Sorular.Remove(sorular);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool SorularExists(int id)
        {
            return _context.Sorular.Any(e => e.ID == id);
        }
    }
}

ogrenciyimProje/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - ogrenciyim</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Business Casual - Start Bootstrap Theme</title>

    <!-- Bootstrap core CSS -->
    <link href="vendor/bootstrap/css/bootstrap.min.css" rel="stylesheet">

    <!-- Custom fonts for this template -->
    <link href="https://fonts.googleapis.com/css?family=Raleway:100,100i,200,200i,300,300i,400,400i,500,500i,600,600i,700,700i,800,800i,900,900i" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Lora:400,400i,700,700i" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="css/business-casual.min.css" rel="stylesheet">
</head>

<body style="background-color:whitesmoke">

    <header style="background-color:lightgrey">
        <nav class="navbar navbar-expand-lg navbar-light py-lg-4" id="mainNav">
            <div class="container">
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarResponsive">
                    <ul class="navbar-nav mx-auto">
                        <li class="nav-item px-lg-4">
                            <a class="nav-link text-uppercase text-expanded" asp-area="" asp-controller="Home" asp-action="Index">Ana Sayfa</a>
                        </li>
                        <li class="nav-item px-lg-4">
                            <a class="nav-link text-uppercase text-expanded" asp-controller="Sorulars" asp-action="Index">Soru Sayfası</a>
                        </li>
                        <li class="nav-item px-lg-4">
                            <a class="nav-link text-uppercase text-expanded" asp-area="" asp-controller="Home" asp-action="Hakkinda">Hakkında</a>
                        </li>
                        <li class="nav-item px-lg-4">
                            <a class="nav-link text-uppercase text-expanded" asp-area="Identity" asp-page="/Account/Manage/Index" title="Manage">Profil</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>

    <div class="container" style="background-color:white">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted" style="background-color:lightgrey">
        <div class="container">
            &copy; 2019 - ogrenciyimProje
        </div>
    </footer>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)

</body>

</html>